# Generated by Django 3.0.6 on 2020-05-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_is_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
    ]
